### PR TITLE
Maximum Likelihood Estimation

### LINKED ISSUE #20: Notebook on maximum likelihood estimation

### PR DESCRIPTION
**Pull request by mridul2899**
Fixes #20 
@PetalsOnWind 
I have completed the sections for the introduction and mathematical formulation of the problem.
Kindly have a look and suggest improvements.
Now, I will be starting with applying maximum likelihood estimation on the probability distributions I mentioned earlier.
Since I've tried to keep the notebook detailed so far, for quick revision purposes, I also plan to include a summary in the end.

### CODE REVIEW

**Comment by PetalsOnWind** [comment]
This looks good so far. You might want to have a section explaining the difference between probability and likelihood, since that's confusing for a beginner.

**Comment by mridul2899** [comment]
Thanks for reviewing! Sure, I'll include a section for explaining the difference.

**Comment by mridul2899** [comment]
@PetalsOnWind
I have completed the section for explaining the difference between probability and likelihood. I've also completed MLE for samples supposedly obtained from Bernoulli Distribution. It would be beneficial if you can review once and suggest improvements/changes.

**Comment by PetalsOnWind** [comment]
For references you can use APA or Chicago format. It makes things look neater.

Suggestions:
1. There seems to be some error in the LaTeX between input cell 8 and 9. Maybe move `$$` to next line.

Seems fine otherwise

**Comment by mridul2899** [comment]
@PetalsOnWind 
Thank you for checking this and especially for finding out the erroneous portion.

I didn't check before how the notebook looks on GitHub, and it turns out that it gets rendered very differently here. Even after adding newlines, in some places, the LaTeX still doesn't render correctly, while it does so on Jupyter. Moreover, the tex code which does get rendered doesn't look equally good as it does on Jupyter. So should I try to optimise its view for directly browsing on GitHub? And if yes, are you aware of any way better than trial and error, without having to make unnecessary commits repetitively?

Regarding referencing - thank you for suggesting. I'll check the two styles and will go ahead with one of them.

**Comment by PetalsOnWind** [comment]
@mridul2899 I am not sure but I think the tex issue will fix up if you move it to a new cell. It might be that github changes the cell type while showing instead of line by line like Jupyter notebook. I am not sure about that. Maybe try and let me know if that works.

**Comment by mridul2899** [comment]
While putting the LaTeX code in separate cells didn't work, I found some other bugs, removing which made things work.
Here's what I changed in the tex code:
- `\begin{align}`...`\end{align}` to `\begin{aligned}`...`\end{aligned}` -> This made the equations get aligned correctly in GitHub
- `\begin{array}`...`\end{array}` to `\begin{matrix}`...`\end{matrix}` -> This made the erroneous equations render correctly

Turns out that `align` should not be used inside a math environment (it creates one itself), but `aligned` can be used inside of it.
An extra tex package needed to be included for `array` (couldn't find a way to do so in Jupyter), but isn't required for `matrix`.

**Comment by mridul2899** [comment]
@PetalsOnWind 
I have completed this notebook and I guess that it is ready to be merged. Kindly review.

**Comment by PetalsOnWind** [comment]
Looks great

**Pull request merged**
