### PR TITLE
Implementation of KNN(K-Nearest-Neighbours) Added

### PR DESCRIPTION
**Pull request by Ritu7683**
@PetalsOnWind Please Review my work. Thank you

### CODE REVIEW

**Comment by Ritu7683** [comment]
@PetalsOnWind  Please Reply

**Comment by PetalsOnWind** [comment]
@Ritu7683 Cite the image sources

**Comment by Ritu7683** [comment]
@PetalsOnWind Do I need to add image sources at the end of the Notebook ?

**Comment by Ritu7683** [comment]
@PetalsOnWind Please Reply

**Comment by PetalsOnWind** [comment]
@Ritu7683 I am sorry for not replying. I merged this PR. You can open a Level 0 issue and fix the image cites

**Pull request merged**
