### PR TITLE
Adding the ANCOVA Notebook.

### PR DESCRIPTION
**Pull request by Rutikab12**
This notebook contain the explanation about the ANCOVA with the help of small example.

### CODE REVIEW

**Comment by PetalsOnWind** [comment]
Closing due to plagiarism
statisticshowto.com/ancova/#:~:text=ANCOVA%20is%20a%20blend%20of,the%20influence%20of%20the%20others.

**Comment by Rutikab12** [comment]
hey should i change the theory of the notebook?. But i have mentioned in the notebook that theory part and dataset is derived from the website. @PetalsOnWind . Please tell otherwise you are free to unassign me from this issue.

**Comment by PetalsOnWind** [comment]
@Rutikab12 I like the general organization of the notebook and would have merged the PR but the notebook has excessive copying (plagiarism) from the link mentioned earlier and I have low tolerance for plagiarism

**Comment by Rutikab12** [comment]
> @Rutikab12 I like the general organization of the notebook and would have merged the PR but the notebook has excessive copying (plagiarism) from the link mentioned earlier and I have low tolerance for plagiarism

Okay. So can i continue or stop here. Continue in the sense try for fresh notebook.

**Comment by PetalsOnWind** [comment]
Whatever you wish. If you want to continue, you have a lot of plagiarism to fix but I like the topic and would like seeing a notebook on it.

**Pull request closed without merging**
