### PR TITLE
Clt notebook 

### PR DESCRIPTION
**Pull request by RiyaMANIT**
Added definition of CLT with its use and assumptions and example
And visualised it by creating a test data set
Later on I drawn different Distributions and how CLT Work for then with increasing its sample size

References i had used during this project:
Central Limit Theorem: https://www.investopedia.com/terms/c/central_limit_theorem.asp
Different Distribution's: https://www.analyticsvidhya.com/blog/2017/09/6-probability-distributions-data-science/
LaTex: https://towardsdatascience.com/write-markdown-latex-in-the-jupyter-notebook-10985edb91fd

### CODE REVIEW

**Comment by PetalsOnWind** [comment]
1. Add more explanations
2. Add more comments
3. Add mathematics
4. Add more graphs

**Comment by RiyaMANIT** [comment]
Hi Maam, Please check my changes and confirm my commit

**Comment by RiyaMANIT** [comment]
Ma'am There is No Folder containing WIP on my Repo, I forked again still no WIF folder found to move my update notebook in order to merge this PR into your Repo

**Comment by PetalsOnWind** [comment]
@RiyaMANIT You had to make a new folder named "WIP" in your own repo.

**Comment by RiyaMANIT** [comment]
> @RiyaMANIT You had to make a new folder named "WIP" in your own repo.

Ma'am I had created new PR with added modified notebook to WIP folder with the changes that you had said
Please merge it Ma'am

**Comment by PetalsOnWind** [comment]
Redundant

**Pull request closed without merging**
