### PR TITLE
Joint Probability distribution, marginal and conditional definitions

### LINKED ISSUE #19: Notebook on joint probability distributions

### PR DESCRIPTION
**Pull request by JanhaviSoni**
Fixes #19

### CODE REVIEW

**Comment by PetalsOnWind** [comment]
1. Move the notebook to the `notebooks` folder. I don't mean to be rude but I have stated that multiple times by now.
2. You can add functions which inputs `distribution-type` or `x` and `y` that let's you calculate marginal and conditional probability distributions. For integration, you can try simulating that with Monte Carlo methods.

**Comment by JanhaviSoni** [comment]
Please check this . I have moved it to notebooks folder.

**Comment by PetalsOnWind** [comment]
@JanhaviSoni Looking forward to seeing more additions!

**Comment by JanhaviSoni** [comment]
Please check this and will be adding one more example problem with user input functionality as you said.

**Comment by PetalsOnWind** [comment]
@JanhaviSoni 

1. Rename `st_images` to `images`
2. Don't copy images from elsewhere. You can easily generate random data to show something. Cite if you copy. Ignore, if you generated graphs in Excel or something.
3. If you haven't understood the topic, some basics are explained [here](https://www.youtube.com/watch?v=JBrmtGDdEmY&ab_channel=ArijitMondal)
4. Add the information about how the things will work for continuous variables
5. Add bivariate normal distribution

**Comment by JanhaviSoni** [comment]
@PetalsOnWind 
1.Added definitions to Joint Probability Distribution for continuous variable and cumulative distribution .
2.Added an example with user input
Please check this.

**Comment by JanhaviSoni** [comment]
@PetalsOnWind  please have a look at this.

**Comment by JanhaviSoni** [comment]
@PetalsOnWind Please have a check if everything is done and can it be merged.

**Comment by PetalsOnWind** [comment]
@JanhaviSoni The text portions look weird on viewing in Github (a lot of "unknown character"). Can you fix that?
Also, add a section on what is Monte Carlo Integration and how to do that.

**Comment by JanhaviSoni** [comment]
Please have a look . I have fixed unknown characters issue.

**Comment by JanhaviSoni** [comment]
I have done all the changes. Please have a look again .

**Comment by PetalsOnWind** [comment]
You added more to Monte Carlo Integration than I was expecting. I think you can just add this to the notebook that you'll follow Monte Carlo Integration for integrating here and make a new notebook with explanations and more graphs for Monte Carlo Integration.

I am merging this PR but you can keep the above points in mind for moving ahead.

**Comment by JanhaviSoni** [comment]
@PetalsOnWind 
It means my next task is a notebook on Monte Carlo Integration. Sorry, I didn't understand what you said . Please brief me about it again.

**Comment by PetalsOnWind** [comment]
@JanhaviSoni Make the next book on Monte Carlo methods which includes Monte Carlo Integration

**Comment by JanhaviSoni** [comment]
Please open this issue and assign it to me .

**Comment by JanhaviSoni** [comment]
@PetalsOnWind Please give a little description and things to be covered in the Monte Carlo methods topic and please open the issue . Also should I keep or delete this merged branch?

**Comment by PetalsOnWind** [comment]
You can keep or delete the branch as per your wish

**Pull request merged**
