### PR TITLE
Added Precision&Recall Notebook

### LINKED ISSUE #11: Notebook on precision and recall
Should include case studies and what happens with precision and recall is high/low.

### PR DESCRIPTION
**Pull request by prit108**
Closes #11  Suggest any additions or changes.

### CODE REVIEW

**Comment by PetalsOnWind** [comment]
Looks good so far. Add sections on what it is means if both are high, one is high one is low and both are low. And how to correct the model if precision/recall is low. Plus an example where a change caused value of precision and/or to increase after some changes.

**Comment by prit108** [comment]
Okay thanks for the review, will complete soon.

**Comment by PetalsOnWind** [comment]
@prit108 Any update?

**Comment by prit108** [comment]
On it.. Will commit in a couple of days.

**Comment by prit108** [comment]
@PetalsOnWind could you recommend some resource for "Improving Precision and Recall"? All I can find are scattered bits on Q&A sites.

**Comment by PetalsOnWind** [comment]
Break up long code cells and add explanations. It looks fine I guess

**Comment by prit108** [comment]
@PetalsOnWind  Done with the requested changes. Kindly re-review.

**Pull request merged**
