### PR TITLE
fix issue #76

### PR DESCRIPTION
**Pull request by Dishita2602**
I have explain and plotted various graph like histogram, pdf plot, confidence interval in some different ways code.

### CODE REVIEW

**Comment by PetalsOnWind** [comment]
1. Add heading to overall notebook
2. Add graph titles to the last graph

**Comment by Dishita2602** [comment]
ok

**Comment by PetalsOnWind** [comment]
@Dishita2602 That name is fine

**Comment by Dishita2602** [comment]
Okay I have added title in last para and now I am doing PR

**Pull request merged**
