### PR TITLE
Added 6 topics in ideas.md

### PR DESCRIPTION
**Pull request by rauniyarbsal**
Hello @PetalsOnWind !! 
I am a participant in GSSOC'21 and  i have added 6 new topics  in your Add topics to ideas.md #2 issue . So, i would request you to check those topics which i have added and assign pull request to me.

### CODE REVIEW

**Comment by rauniyarbsal** [comment]
@PetalsOnWind By mistake I clicked on close with comment, now again I opened it.
Sorry for inconvenience caused

**Comment by rauniyarbsal** [comment]
@PetalsOnWind  mam please reply whether the topics i have added is correct or not because this will be my first pr if you assign it to me!!

**Comment by PetalsOnWind** [comment]
> -Logistic Regression
> - K-Means Clustering
> - K Nearest Neighbours
> - Data Visualization

Are unnecessary. I'll merge if you remove them

**Review by rauniyarbsal — COMMENTED** [review]
@PetalsOnWind  mam is this okay?

**Comment by rauniyarbsal** [comment]
@PetalsOnWind  i didn't understand mam !! 
Mam , i think it still didn't get added in ideas.md file.

**Pull request merged**
