### PR TITLE
notebooks/data_summary_breast_cancer.ipynb

### PR DESCRIPTION
**Pull request by sakshi012000**
@PetalsOnWind Data summary and statistical analysis on breast cancer analysis. Please review my PR.

### CODE REVIEW

**Comment by PetalsOnWind** [comment]
Can you link all sources you referred to while making the notebooks?

**Comment by sakshi012000** [comment]
yes sure, should I add these at the end of my notebook?

**Comment by sakshi012000** [comment]
@PetalsOnWind  I have added the references. Please review it and tell me of any other required modifications. Thankyou.

**Comment by PetalsOnWind** [comment]
Just add a heading and correct the spelling in the notebook name

**Comment by sakshi012000** [comment]
@PetalsOnWind  I have corrected the spelling and gave a heading. please review it.

**Pull request merged**
