### PR TITLE
Dummy Variables

### PR DESCRIPTION
**Pull request by basilisk-2001**
@PetalsOnWind  I hope this time it works ...

### CODE REVIEW

**Comment by PetalsOnWind** [comment]
The branch problem is resolved but you still have a lot of work to do

**Comment by basilisk-2001** [comment]
@PetalsOnWind  plz help ...I'm new to this open source platform ...plz help me resolve these issues...guide me at least as I want to work hard on these projects...

**Comment by PetalsOnWind** [comment]
@basilisk-2001 DM me on gitter. I'll share some material on what I would like to be done

**Comment by basilisk-2001** [comment]
@PetalsOnWind this one...here

**Comment by PetalsOnWind** [comment]
@basilisk-2001 If you have done anything, you need to merge the branch to patch-1 in your repo before I can merge this PR

**Comment by PetalsOnWind** [comment]
Incomplete
-Will delete if no progress in 5 days

**Comment by basilisk-2001** [comment]
@PetalsOnWind  I guess this issue was regarding showing some use of dummy variables ...can you plz explain what changes I need to make ???

**Pull request merged**
