### PR TITLE
Readme file enhanced

### PR DESCRIPTION
**Pull request by anirudhsai20**
I have added a list of all the programs in which this project was a part of.

### CODE REVIEW

**Comment by anirudhsai20** [comment]
Hi! Please check my pull request and inform me whether it needs any modification.

**Comment by anirudhsai20** [comment]
Hi! Please check my pull request.

**Comment by PetalsOnWind** [comment]
Stock PR. Not merging this since you didn't even bother to read the README and see this project was also a part of KWOC

**Comment by anirudhsai20** [comment]
Hi. I am sorry I did not include KWOC in the list. It was a sincere mistake. Please give me a chance to correct it.

**Pull request closed without merging**
