### PR TITLE
Monte Carlo methods

### PR DESCRIPTION
**Pull request by JanhaviSoni**
#27

### CODE REVIEW

**Comment by JanhaviSoni** [comment]
@PetalsOnWind I have started by adding Monte Carlo integration and will soon be updating with more changes.

**Comment by JanhaviSoni** [comment]
@PetalsOnWind  Please have a look at this.

**Comment by JanhaviSoni** [comment]
@PetalsOnWind Please have a look and check if its complete and can be merged .

**Comment by JanhaviSoni** [comment]
@PetalsOnWind Please check .

**Comment by PetalsOnWind** [comment]
Looks good

**Pull request merged**
