### PR TITLE
Adding notebook for Time series visualization

### PR DESCRIPTION
**Pull request by naman-jajani**
I have made a new notebook which consists of time series visualization methods.

### CODE REVIEW

**Comment by PetalsOnWind** [comment]
1. Explain what trend, seasonality and noise is in context of time series
1. Simulate some data to show that changes the shape
1. Add some explanations

**Comment by naman-jajani** [comment]
Yes,I'll do that in a different notebook,i only made that notebook for
visualization,
Do i have to make only 1 notebook?

**Comment by PetalsOnWind** [comment]
Well, you can make as many notebooks as you want. But currently your notebook does not have sufficient content to be merged. You can check out other merged notebooks to see how the notebook needs to look like.

**Comment by naman-jajani** [comment]
Okay I'll add those things surely,
I thought of making separately so that's why i just committed that,
Surely I'll add those stuffs to it.

**Comment by PetalsOnWind** [comment]
Incomplete
-Will be deleted if no other revisions are done in 5 days

**Pull request merged**
