### PR TITLE
changed intro_numpy,pandas and matplotlib with best example and graph

### PR DESCRIPTION
**Pull request by Bhavik-Ardeshna**
#3 
Added new graph and with some realife example of numpy pandas and matplotlib . And also given section for each topic

Plz merge this after 1st march becauz I want this PR to count in GSSoC'21

:)

### CODE REVIEW

**Comment by Bhavik-Ardeshna** [comment]
Plz merge for GSSOC'21
I really worked hard for goog example and content

**Comment by PetalsOnWind** [comment]
@Bhavik-Ardeshna Some of the graphs look really good. However it'll be great if you can add more documentation and explanation of what you are doing

**Comment by Bhavik-Ardeshna** [comment]
ok I'll make in couple of days by going through it. 😀

**Comment by Bhavik-Ardeshna** [comment]
@PetalsOnWind added documentation where its needed

**Pull request merged**
