### PR TITLE
Added Correlation Notebook

### PR DESCRIPTION
**Pull request by TarunMANIT**
Added Correlation definition with proper examples and mathematical expressions, visualized it with random data and finally calculated Correlation between the stock instruments based on their close prices

References i had used during this project:
Covariance: https://www.statisticshowto.com/covariance/
LaTex: https://towardsdatascience.com/write-markdown-latex-in-the-jupyter-notebook-10985edb91fd
Correlation: https://www.investopedia.com/terms/c/correlation.asp
Futures: https://zerodha.com/varsity/module/futures-trading/
Options: https://zerodha.com/varsity/module/option-theory/

### CODE REVIEW

**Comment by PetalsOnWind** [comment]
Add how-to calculate standard error for correlation

**Comment by TarunMANIT** [comment]
Ma'am I am facing issue in pushing to https://github.com/TarunMANIT/Statistics-and-Econometrics-for-Data-Science/tree/correlation-Notebook

when I type  git checkout correlation-Notebook on cmd  it shows error: pathspec 'TarunMANIT:correlation-Notebook' did not match any file(s) known to git

**Comment by PetalsOnWind** [comment]
@TarunMANIT Make a new branch and commit all changes to that. Then on github merge it with the correlation-Notebook

**Comment by TarunMANIT** [comment]
> @TarunMANIT Make a new branch and commit all changes to that. Then on github merge it with the correlation-Notebook

Yes, Ok Ma'am
Please confirm, I have one commit right now?
As suggested in KWoC portal we should have at least one commit for Mid Evaluation

**Comment by PetalsOnWind** [comment]
@TarunMANIT You'll need to merge the branches in your repo. Then it will be reflected here. Currently I don't see any new commits

**Comment by TarunMANIT** [comment]
> @TarunMANIT You'll need to merge the branches in your repo. Then it will be reflected here. Currently I don't see any new commits

Ma'am, I completed my Notebook and Added Heatmap for correlation with proper documentation and neat explanation,
But I am facing issue in Merging and commiting new branch
Please share resources regarding

**Comment by PetalsOnWind** [comment]
https://www.atlassian.com/git/tutorials

**Comment by TarunMANIT** [comment]
Ma'am I had added Heatmap with proper documentation
Please confirm my commit

**Comment by PetalsOnWind** [comment]
You haven't added p-value calculations for correlation. There is no point considering correlation if it is not significant so p-value is important.

**Comment by TarunMANIT** [comment]
> You haven't added p-value calculations for correlation. There is no point considering correlation if it is not significant so p-value is important.

Yes, Ma'am I will be adding Standard error and p-value for it I had gathered research papers  
For now just confirm my commit Ma'am

**Comment by PetalsOnWind** [comment]
I can see your commit

**Comment by TarunMANIT** [comment]
> I can see your commit

Thank you Ma'am
But it's not showing on dashboard
It would be great if you could share resources regarding standard error for correlation
As i found 2 different methods to calculate standard error for correlation

**Comment by PetalsOnWind** [comment]
Implement both methods

**Comment by TarunMANIT** [comment]
> Implement both methods

Ok Ma'am

**Comment by PetalsOnWind** [comment]
@TarunMANIT Move the notebook to WIP folder so I can merge this PR and continue working

**Comment by TarunMANIT** [comment]
> @TarunMANIT Move the notebook to WIP folder so I can merge this PR and continue working

Yes Ma'am 
Can I move/upload the modified notebook without using CMD line?
My laptop is crashed am using it in my sister's laptop, so facing issue in moving using CMD line

**Comment by TarunMANIT** [comment]
Ma'am, I had created another branch(Correlation) in which I had uploaded my updated notebook in WIP folder and opened PR, Please merge that PR

**Comment by PetalsOnWind** [comment]
@TarunMANIT  Merged that PR

**Pull request closed without merging**
