### PR TITLE
Linear Discriminant Analysis file added

### PR DESCRIPTION
**Pull request by jainyk**
Please have a review of the notebook and let me know if any changes required.

### CODE REVIEW

**Comment by PetalsOnWind** [comment]
@jainyk 
1. Images are not showing
2. Insufficient explanations with coes

**Comment by jainyk** [comment]
Will modify it.

**Comment by PetalsOnWind** [comment]
@jainyk any update?

**Comment by jainyk** [comment]
Will be updating within 1-2 days.

**Comment by jainyk** [comment]
please have a review.

**Pull request merged**
