### PR TITLE
Data_Summary #12

### PR DESCRIPTION
**Pull request by skybluee2001**
Data Summary and Statistical Analysis on Diabetes #12

### CODE REVIEW

**Comment by skybluee2001** [comment]
@PetalsOnWind I have made a PR; kindly review it.

**Comment by PetalsOnWind** [comment]
Change images to LaTeX text. Looks good otherwise

**Comment by skybluee2001** [comment]
@PetalsOnWind sure I will update it

**Comment by skybluee2001** [comment]
@PetalsOnWind, I have changed the images to LaTeX text. Kindly review it. 
Issue #12

**Comment by skybluee2001** [comment]
@PetalsOnWind, let me know if any further changes are required :)

**Comment by skybluee2001** [comment]
@PetalsOnWind, please let me know if any modifications are required. If there are no further changes required, kindly merge my PR as the period for contributing to open source ends on 31st March. This is my first PR, so it would be great if it could get merged before that.

**Pull request merged**
