### PR TITLE
Create Heteroscedasticty.ipynb

### PR DESCRIPTION
**Pull request by SmilingYogi**
Notebook on heteroscedasticity #10
Will keep adding. Kindly review

### CODE REVIEW

**Comment by PetalsOnWind** [comment]
Looks fine. I hope that you do plan to manually re-create BP and GQ tests.

I would also like graphs for all the cases mentioned such as:
> Presence of outliers in the observations (stock prices)
>Incorrect transformation of data used for the regression model
>When regression model is itself wrongly specified
>Skewness in distribution of regressor variables.

**Comment by SmilingYogi** [comment]
> I would also like graphs for all the cases mentioned such as:
> 
> > Presence of outliers in the observations (stock prices)
> > Incorrect transformation of data used for the regression model
> > When regression model is itself wrongly specified
> > Skewness in distribution of regressor variables.
 
@PetalsOnWind I am not able to find good graphs for all the cases. So, I am thinking of providing brief explanation for each case (like in Basic Econometrics by Damodar Gujarati)

**Comment by PetalsOnWind** [comment]
@SmilingYogi You can simulate examples to draw graphs. For example.
>Presence of outliers in the observations (stock prices)
Generally n random numbers and add n/m numbers to the series that are fairly obviously outliers. For example, have n numbers between 0 and 10 and n/m numbers between 10 and 15. Choose m any value such as 5.

>Incorrect transformation of data used for the regression model
Have the true relationship as log but the graphed relationship as linear so that there happens to be heteroskedasticity.

>When regression model is itself wrongly specified
Let the true relationship be `y = a*x1 + b*x2 + c` but the estimated relationship be `y = dx1 + e` so that the variance of the error term is not constant, but have the correlation between x1 and x2 low to avoid endogeneity.

>Skewness in distribution of regressor variables
Just generate a skewed distribution while plotting

**Comment by SmilingYogi** [comment]
Understood. Will do

**Comment by SmilingYogi** [comment]
@PetalsOnWind I have added examples for all the cases. Please take a look!

**Comment by PetalsOnWind** [comment]
Looks good.
Just add mathematical formulations of BP and GQ test and implement them from scratch and it is ready to be merged.

**Comment by PetalsOnWind** [comment]
@SmilingYogi Have a look at the previous comment

**Comment by SmilingYogi** [comment]
Yeah, I will try to do it by today EOD

**Comment by SmilingYogi** [comment]
@PetalsOnWind I have added the manual recreations of BP and GQ tests.
Take a look now!

**Comment by PetalsOnWind** [comment]
Merging for now although I want to see more mathematical details added to the notebook

**Pull request merged**
