### PR TITLE
Commit on ANOVA

### PR DESCRIPTION
**Pull request by PriyaJ28**
I have added a notebook containing the implementation of 1-way ANOVA.

### CODE REVIEW

**Comment by PetalsOnWind** [comment]
It looks good so far. I can see that you borrowed significant portions from [this](https://towardsdatascience.com/1-way-anova-from-scratch-dissecting-the-anova-table-with-a-worked-example-170f4f2e58ad) and I would like you to change or add enough so that its distinguishable. 

Suggestions:
1. More comments in the good, explaining what you are doing. Ideally, every cell should have at least one comment.
1. When generating data, let a size of (len(L), 7) instead of the list thing you are doing right now.
2. Calculate the min and max using functions instead of writing after visual inspection. Since, it's not actually possible to visually inspect for a large dataset.
3. Add violen plots (plus their interpretation) along with box plots and compare both. 
3. From where are you following the notation for the null hypothesis? It looks different from the notations that I have been exposed to. mu is generally used to denote mean so I don't understand why you added M.
4. You can add some assumptions for doing ANOVA
5. You have made the necessary steps for ANOVA but you haven't made a function that would generate the ANOVA table (like the table of `sm.stats.anova_lm(lm)`. I would like you to implement a function that would take a dataframe (or some x and y) and return an ANOVA table. First try implementing it just like a function. Then try implement using OOP so that it is possible to extract individual values from the table.
6. Move the notebook to the `notebooks` folder
7. Add pairwise mean comparison through Tukey-Kramer test (Also add about the difference between Tukey and Tukey-Kramer tests). Again do it 3 ways: normal, using a single function, using OOP.
8. Explore more the documentation of the functions you used. 
7. Explain more about degrees of freedom
8. Add why is the test stat a F-test (Answer: Sum of squares follow chi-sq test and then find how two chi-sq relate to F)
9. Explain why the distribution was F(4, 30)
9. Proofread more. You mentioned five stores but in at least I found mention of 3 groups (too much copy/pasting?)
10. Do everything all over again by setting the prices different (eg 9-14 for A, 5-9 for B, etc) so that you know that you can reject the null hypothesis. 

I think that's all from me for now. If these points are fixed, I think we are ready to merge.

**Comment by PetalsOnWind** [comment]
For all functions that you define, define it in the form
```
def func(a,b):
    """
        What this function does.
         Inputs:
         a: What is a? int, string or float?
         b: What is b? And what is its format?

         Outputs:
          x: or whatever the output is
    """
    x = a+b
    return x
```

Otherwise, this is coming out very well. Let me know when you think it is ready to be merged.

**Comment by PriyaJ28** [comment]
I have done the changes. Thank you for the suggestions.

**Comment by PetalsOnWind** [comment]
@PriyaJ28 Looks good! I am merging this PR.

**Pull request merged**
