### PR TITLE
Added Monte Carlo Notebook

### PR DESCRIPTION
**Pull request by adityapiyush26**
added the Monte Carlo notebook

### CODE REVIEW

**Comment by PetalsOnWind** [comment]
@adityapiyush26 

1. Add all notebooks to the `notebooks` folder.
2. Remove empty cells in final commit
3. Add comments to explain what you are doing

**Comment by adityapiyush26** [comment]
Sure I will do it

**Comment by adityapiyush26** [comment]
@PetalsOnWind please check and let me know if it is fine.

**Comment by PetalsOnWind** [comment]
@adityapiyush26 Looks good. Now you can add how to simulate integration using monte carlo and how to do hypothesis testing using monte carlo.

**Comment by PetalsOnWind** [comment]
@adityapiyush26 Any update?

**Comment by adityapiyush26** [comment]
@PetalsOnWind yeah I'm learning new topics, I will add it in 2 days

**Comment by PetalsOnWind** [comment]
@adityapiyush26 Move this to a new folder name "WIP" for it to be merged.

**Comment by adityapiyush26** [comment]
@PetalsOnWind  I have done it please check

**Pull request merged**
