### PR TITLE
Statistical Notebook

### PR DESCRIPTION
**Pull request by anjiii-18**
@PetalsOnWind I have uploaded my notebook. Kindly review it.

### CODE REVIEW

**Comment by PetalsOnWind** [comment]
Comments
1. Comment out the first line and re-run the code. Installation comments take up too much unnecessary space
2. Add more explanations. Why are you drawing the graphs? What inference can you draw out of them? Why choose that particular kind of graph?
3. Add why you are choosing a dataset. Describe the dataset, what are the variables, how they are measured, etc. 
4. Add maths for CLT. What are the assumptions of CLT? What is the asymptotic behaviour? Why we see the asymptotic behaviour?
5. Same for confidence intervals
6. Shift probability parts to another notebook

**Comment by anjiii-18** [comment]
@PetalsOnWind I will do the required changes.

**Comment by anjiii-18** [comment]
@PetalsOnWind I have done the required changes, and uploaded two notebooks. Kindly review it.

**Comment by anjiii-18** [comment]
@PetalsOnWind By mistake I clicked on close PR, now again I opened it.
Sorry for inconvenience caused.

**Comment by anjiii-18** [comment]
@PetalsOnWind I made changes in Statistical  & Probability Notebook : Part 1 as the latex characters were showing an error in git view, but not in Google Collab, and thus I needed to again delete and upload until the perfection was achieved.
Kindly review both the notebooks now.
Statistical  & Probability Notebook : Part 1
Statistical  & Probability Notebook : Part 2

**Comment by PetalsOnWind** [comment]
Add overall heading to the notebooks

**Comment by anjiii-18** [comment]
@PetalsOnWind I have added overall headings to notebook. Kindly review. :)

**Pull request merged**
