### PR TITLE
Create Baye's Theorem Notebook

### LINKED ISSUE #21: Notebook on Bayes Theorem

### PR DESCRIPTION
**Pull request by charchit95**
Fix #21

### CODE REVIEW

**Comment by PetalsOnWind** [comment]
Suggestions:
1. No plagiarism. You have copied a lot of portions from [this](https://www.mathsisfun.com/data/bayes-theorem.html). This is a simple JEE topic. You can easily make up your own example. 
2. Don't copy tables. Search on how to incorporate LaTeX in Jupyter Notebook and type using LaTeX.
3. Remove all the headings and let most of the notebook be normal text.

**Comment by charchit95** [comment]
Ok ,Sure I will update the example and format.

**Comment by PetalsOnWind** [comment]
Closed due to lack of activity

**Comment by ayushjha952** [comment]
Can I work on this issue ?
Can you assign it to me.

**Pull request closed without merging**
